SELECT REPLACE(state, "AL", "Alabama") FROM shootings;
SELECT REPLACE(state, "AK", "Alaska") FROM shootings;
SELECT REPLACE(state, "AZ", "Arizona") FROM shootings;
SELECT REPLACE(state, "AR", "Arkansas") FROM shootings;
SELECT REPLACE(state, "CA", "California") FROM shootings;
SELECT REPLACE(state, "CO", "Colorado") FROM shootings;
SELECT REPLACE(state, "CT", "Connecticut") FROM shootings;
SELECT REPLACE(state, "DE", "Delaware") FROM shootings;
SELECT REPLACE(state, "DC", "District of Columbia") FROM shootings;
SELECT REPLACE(state, "FL", "Florida") FROM shootings;
SELECT REPLACE(state, "GA", "Georgia") FROM shootings;
SELECT REPLACE(state, "HI", "Hawaii") FROM shootings;
SELECT REPLACE(state, "ID", "Idaho") FROM shootings;
SELECT REPLACE(state, "IL", "Illinois") FROM shootings;
SELECT REPLACE(state, "IN", "Indiana") FROM shootings;
SELECT REPLACE(state, "IA", "Iowa") FROM shootings;
SELECT REPLACE(state, "KS", "Kansas") FROM shootings;
SELECT REPLACE(state, "KY", "Kentucky") FROM shootings;
SELECT REPLACE(state, "LA", "Louisiana") FROM shootings;
SELECT REPLACE(state, "ME", "Maine") FROM shootings;
SELECT REPLACE(state, "MD", "Maryland") FROM shootings;
SELECT REPLACE(state, "MA", "Massachusetts") FROM shootings;
SELECT REPLACE(state, "MI", "Michigan") FROM shootings;
SELECT REPLACE(state, "MN", "Minnesota") FROM shootings;
SELECT REPLACE(state, "MS", "Mississippi") FROM shootings;
SELECT REPLACE(state, "MO", "Missouri") FROM shootings;
SELECT REPLACE(state, "MT", "Montana") FROM shootings;
SELECT REPLACE(state, "NE", "Nebraska") FROM shootings;
SELECT REPLACE(state, "NV", "Nevada") FROM shootings;
SELECT REPLACE(state, "NH", "New Hampshire") FROM shootings;
SELECT REPLACE(state, "NJ", "New Jersey") FROM shootings;
SELECT REPLACE(state, "NM", "New Mexico") FROM shootings;
SELECT REPLACE(state, "NY", "New York") FROM shootings;
SELECT REPLACE(state, "NC", "North Carolina") FROM shootings;
SELECT REPLACE(state, "ND", "North Dakota") FROM shootings;
SELECT REPLACE(state, "OH", "Ohio") FROM shootings;
SELECT REPLACE(state, "OK", "Oklahoma") FROM shootings;
SELECT REPLACE(state, "OR", "Oregon") FROM shootings;
SELECT REPLACE(state, "PA", "Pennsylvania") FROM shootings;
SELECT REPLACE(state, "RI", "Rhode Island") FROM shootings;
SELECT REPLACE(state, "SC", "South Carolina") FROM shootings;
SELECT REPLACE(state, "SD", "South Dakota") FROM shootings;
SELECT REPLACE(state, "TN", "Tennessee") FROM shootings;
SELECT REPLACE(state, "TX", "Texas") FROM shootings;
SELECT REPLACE(state, "UT", "Utah") FROM shootings;
SELECT REPLACE(state, "VT", "Vermont") FROM shootings;
SELECT REPLACE(state, "VA", "Virginia") FROM shootings;
SELECT REPLACE(state, "WA", "Washington") FROM shootings;
SELECT REPLACE(state, "WV", "West Virginia") FROM shootings;
SELECT REPLACE(state, "WI", "Wisconsin") FROM shootings;
SELECT REPLACE(state, "WY", "Wyoming") FROM shootings;
SELECT REPLACE(state, "AS", "American Somoa") FROM shootings;
SELECT REPLACE(state, "GU", "Guam") FROM shootings;
SELECT REPLACE(state, "MP", "Northern Mariana Islands") FROM shootings;
SELECT REPLACE(state, "PR", "Puerto Rico") FROM shootings;
SELECT REPLACE(state, "UM", "United States Minor Outlying Islands") FROM shootings;
SELECT REPLACE(state, "VI", "Virgin Islands") FROM shootings;
SELECT REPLACE(state, "AA", "Armed Forces Americas") FROM shootings;
SELECT REPLACE(state, "AP", "Armed Forces Pacific") FROM shootings;
SELECT REPLACE(state, "AE", "Armed Forces Others") FROM shootings;